name: CI
on:
  pull_request:
    branches:
      - main
jobs:
  ci:
    name: CI
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install .NET SDKs
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: |
            3.1.x
            5.0.x
            6.0.x

      - name: Run Cake
        uses: cake-build/cake-action@v1
        with:
          target: CI
          cake-version: tool-manifest
